### ISSUE TITLE
Typo in application description

### ISSUE THREAD

**Issue by thomasphorton** [awslabs/real-time-web-analytics-with-kinesis#1]
https://github.com/awslabs/real-time-web-analytics-with-kinesis/blob/e204e0826f7458cddc1b38fc02594a0a76a83882/deployment/real-time-web-analytics-with-kinesis.template#L794

Kinesis is misspelled in the application description.

**Comment by thomasphorton** [comment]
Testing out commenting on an internally-closed TT.

**Comment by shahid-malik** [comment]
Inserting new VPC parameters
Inserting existing VPC parameters
Inserting new VPC resources
Removing VPC resources placeholder for existing VPCs
Updating subnet references for new VPC template
sed -i '' -e s/%%ALB_SUBNET0%%/Subnet0/g /home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/deployment/dist/real-time-web-analytics-with-kinesis.template
sed: can't read : No such file or directory
sed -i '' -e s/%%ALB_SUBNET1%%/Subnet1/g /home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/deployment/dist/real-time-web-analytics-with-kinesis.template
sed: can't read : No such file or directory
sed -i '' -e s/%%EC2_SUBNET0%%/Subnet0/g /home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/deployment/dist/real-time-web-analytics-with-kinesis.template
sed: can't read : No such file or directory
sed -i '' -e s/%%EC2_SUBNET1%%/Subnet1/g /home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/deployment/dist/real-time-web-analytics-with-kinesis.template
sed: can't read : No such file or directory
Updating subnet references for existing VPC template
sed -i '' -e s/%%ALB_SUBNET0%%/Subnet0/g /home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/deployment/dist/real-time-web-analytics-with-kinesis-existing-vpc.template
sed: can't read : No such file or directory
sed -i '' -e s/%%ALB_SUBNET1%%/Subnet1/g /home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/deployment/dist/real-time-web-analytics-with-kinesis-existing-vpc.template
sed: can't read : No such file or directory
sed -i '' -e s/%%EC2_SUBNET0%%/Subnet2/g /home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/deployment/dist/real-time-web-analytics-with-kinesis-existing-vpc.template
sed: can't read : No such file or directory
sed -i '' -e s/%%EC2_SUBNET1%%/Subnet3/g /home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/deployment/dist/real-time-web-analytics-with-kinesis-existing-vpc.template
sed: can't read : No such file or directory
Updating code source bucket in template with solutions
sed -i '' -e s/%%BUCKET_NAME%%/solutions/g /home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/deployment/dist/real-time-web-analytics-with-kinesis.template
sed: can't read : No such file or directory
sed: can't read : No such file or directory
./build-s3-dist.sh: line 84: cd: /home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/source/wasa: No such file or directory
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/package.json'
npm WARN deployment No description
npm WARN deployment No repository field.
npm WARN deployment No README data
npm WARN deployment No license field.
npm ERR! Linux 4.4.0-1062-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/ubuntu/try2/real-time-web-analytics-with-kinesis/deployment/package.json'
npm ERR! enoent This is most likely not a problem with npm itself

**Comment by thomasphorton** [comment]
@shahid-malik if you are still seeing this error, could you open a new ticket?
