### ISSUE TITLE
Unable to launch CF script

### ISSUE THREAD

**Issue by collinforrester** [awslabs/real-time-web-analytics-with-kinesis#3]
I'm launching this as is and it seems that the ec2 instances in the target group for the ALB can never establish a healthy check.  So it will continuously just spin instances in and out of the group.

I'm launching it into a fresh VPC and changed nothing on the template.

**Comment by vijaysat1** [comment]
Hi,
Can you provide more information on the region and any logs thats generated, and please verify whether its happening in another region in your account where the resources are available and whether the scenario is replicable.
The reported issue was analyzed in region-oregon, unable to replicate the scenario. 

<img width="1034" alt="screen shot 2018-10-12 at 11 28 41 am" src="https://user-images.githubusercontent.com/40778802/46878975-ce428800-ce12-11e8-9d59-22aa8ac533be.png">
<img width="1223" alt="screen shot 2018-10-12 at 11 28 57 am" src="https://user-images.githubusercontent.com/40778802/46878976-ce428800-ce12-11e8-9974-4c5287be030b.png">

Thank You

**Comment by collinforrester** [comment]
I can tell you it's us-east-1 , no logs at the moment

**Comment by vijaysat1** [comment]
A fix has been deployed and us-east-1 should function as needed now. Thanks for your comments to address the issue!

**Comment by georgebearden** [comment]
Hey @collinforrester - Fancy running into you here :) Just cleaning up some old issues across solutions. This issue should have been addressed. Please let me know if this is not the case. Cheers.
